# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541500e0693125e60dc0a3072718c13dd2e5e0106c5a481498aa31548efce9896b41069eb9ab15d22e304743df402f674f5126e2e21ec19533f86f4bdeb13b20

test:
  secret_key_base: 5bd0081139a5f39dc8049750fcde7175fdbeb059c7029d8815f3d1ad52d8b709498d1d9167fddc922ae1922fc9ae472a59b995ce37f13b543d086fc5af525324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
